<?php
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use PostNL\HyvaCheckout\Api\CheckoutFieldsApi;
use PostNL\HyvaCheckout\ViewModel\CheckoutView;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var CheckoutView $checkoutView */

$checkoutView = $viewModels->require(CheckoutView::class);
?>

<script>
    function postnlAddressValidation(wire, options = {}) {
        let inputChangeTimeout = null;

        return {
            address: {
                postcode: wire.address.postcode,
                postnl_housenumber: wire.address.postnl_housenumber,
                postnl_housenumber_addition: wire.address.postnl_housenumber_addition,
                country_id: wire.address.country_id
            },

            searches: 0,
            postcodeRegex: /[1-9][0-9]{3}\s*[a-z]{2}/i,
            houseNumberRegex: /[1-9]\d{0,4}(?:\D.*)?$/i,

            initialize: function() {
                options = Object.assign(this.getOptions(), options);

                this.$nextTick(() => {
                    const postcodeField = this.$root.querySelector('input[name$="[postcode]"]');
                    if (postcodeField) {
                        postcodeField.addEventListener('blur', () => {
                            const value = postcodeField.value;
                            this.onChangeInput('postcode', value, this.address.postcode);
                            this.address.postcode = value;
                        });
                    }
                });
            },

            setCountry() {
                const newValue = this.$event.target.value;
                this.onChangeInput('country_id', newValue, this.address.country_id);
                this.address.country_id = newValue;
            },

            setHouseNumber() {
                const newValue = this.$event.target.value;
                this.onChangeInput('postnl_housenumber', newValue, this.address.postnl_housenumber);
                this.address.postnl_housenumber = newValue;
            },

            setHouseNumberAddition() {
                const newValue = this.$event.target.value;
                this.onChangeInput('postnl_housenumber_addition', newValue, this.address.postnl_housenumber_addition);
                this.address.postnl_housenumber_addition = newValue;
            },

            setPostcode() {
                const newValue = this.$event.target.value;
                this.onChangeInput('postcode', newValue, this.address.postcode);
                this.address.postcode = newValue;
            },

            onChangeInput: async function(ref, newValue, previousValue) {

                if (typeof ref !== 'string') return;

                clearTimeout(inputChangeTimeout);

                const postcode = (ref === 'postcode') ? newValue.trim() : this.address.postcode.trim();
                const houseNumber = (ref === 'postnl_housenumber') ? newValue.trim() : this.address.postnl_housenumber.trim();

                if (ref === 'postcode' && !this.postcodeRegex.test(postcode)) {

                    const postcodeField = this.$root.querySelector('#shipping-postcode');

                    if (postcodeField) {
                        postcodeField.value = '';
                        postcodeField.focus();
                    }

                    const streetField = this.$root.querySelector('input[name$="[street][]"]');
                    if (streetField) {
                        if (this.address.country_id === 'NL') {
                            streetField.value = '';
                        }
                    }

                    this.address.postcode = '';
                    wire.set('address.postcode', '');

                    const isDutchAddress = this.address.country_id === 'NL';

                    const updatedAddress = {
                        street: isDutchAddress ? '' : this.address.street,
                        houseNumber: this.address.postnl_housenumber,
                        houseNumberAddition: this.address.postnl_housenumber_addition,
                        postcode: '',
                        city: ''
                    };

                    wire.set('address.<?= $escaper->escapeJs(CheckoutFieldsApi::POSTNL_ADDRESS) ?>', JSON.stringify(updatedAddress));

                    this.dispatchMessage('<?= $escaper->escapeJs(__('Please enter a valid Dutch postcode (e.g. 1234 AB).')) ?>');

                    return;
                }

                try {
                    const validationResults = await Promise.all(
                        Object.values(options.validators).map(fn => fn(ref, newValue, previousValue, options))
                    );

                    if (validationResults.every(r => r === true)) {
                        inputChangeTimeout = setTimeout(async () => {
                            const postcode = this.address.postcode.trim();
                            const postcodeField = this.$root.querySelector('input[name$="[postcode]"]');
                            const houseNumber = this.address.postnl_housenumber.trim();
                            const url = `<?= $escaper->escapeJs($checkoutView->getCheckoutUrl('address_postcode')) ?>`;

                            if (!this.postcodeRegex.test(postcode)) {
                                this.dispatchMessage('<?= $escaper->escapeJs(__('Please enter a valid Dutch postcode (e.g. 1234 AB).')) ?>');
                                if (postcodeField) {
                                    postcodeField.focus();
                                }
                                return;
                            }

                            if (!postcode || !houseNumber) {
                                return;
                            }

                            const apiResponse = await fetch(url + '?' + new URLSearchParams({
                                postcode: postcode,
                                housenumber: houseNumber
                            }));

                            const response = await apiResponse.json();

                            if (response.status !== undefined) {
                                let message = '<?= $escaper->escapeJs(__('Unexpected error occurred. Please fill in the address details manually.')) ?>';
                                if (response.status === 'error' && response.error !== undefined) {
                                    message = response.error;
                                }
                                if (response.status === false) {
                                    message = '<?= $escaper->escapeJs(__('Sorry, we could not find your address with the zipcode and housenumber combination (%s). Please check the entered postcode and house number and correct them where necessary.')) ?>'
                                        .replace('%s', postcode + ' / ' + houseNumber);

                                    response.status = 'warning';

                                    this.$nextTick(() => {
                                        const streetField = this.$root.querySelector('input[name$="[street][]"]');
                                        const houseNumberField = this.$root.querySelector('input[name$="[postnl_housenumber]"]');
                                        const postcodeField = this.$root.querySelector('input[name$="[postcode]"]');

                                        if (streetField) streetField.value = '';

                                        if (ref === 'postnl_housenumber') {
                                            if (houseNumberField) {
                                                houseNumberField.value = '';
                                                houseNumberField.focus();
                                            }
                                            this.address.postnl_housenumber = '';
                                            wire.set('address.postnl_housenumber', '');
                                        } else if (ref === 'postcode') {
                                            if (postcodeField) {
                                                postcodeField.value = '';
                                                postcodeField.focus();
                                            }
                                            this.address.postcode = '';
                                            wire.set('address.postcode', '');
                                        }
                                    });

                                    wire.set('address.<?= $escaper->escapeJs(CheckoutFieldsApi::POSTNL_ADDRESS) ?>', JSON.stringify({
                                        street: '',
                                        houseNumber: ref === 'postnl_housenumber' ? '' : houseNumber,
                                        houseNumberAddition: this.address.postnl_housenumber_addition,
                                        postcode: ref === 'postcode' ? '' : postcode,
                                        city: ''
                                    }));
                                }
                                this.dispatchMessage(message, response.status);
                                return;
                            }

                            this.errorMessage = '';

                            const addressLocal = this.getAddressParts(response);
                            wire.set('address.<?= $escaper->escapeJs(CheckoutFieldsApi::POSTNL_ADDRESS) ?>', JSON.stringify(addressLocal));

                        }, options.validationTimeout);

                        return true;
                    }

                    return false;
                } catch (error) {
                    this.dispatchMessage(error.message || error);
                }

            },

            getAddressParts: function (address) {
                const houseNumber = `${address.houseNumber || ''}`,
                    houseNumberAddition = this.address.postnl_housenumber_addition;

                return {
                    street: address.streetName,
                    houseNumber: houseNumber,
                    houseNumberAddition: houseNumberAddition,
                    postcode: address.postalCode,
                    city: address.city
                };
            },

            getOptions: function() {
                return {
                    validationTimeout: 1500,

                    validators: {
                        validateValidAddressInput: (ref, value) => {
                            if (ref === "<?= $escaper->escapeJs(\Magento\Quote\Api\Data\AddressInterface::KEY_POSTCODE) ?>") {
                                return !value || this.postcodeRegex.test(value);
                            }
                            else if (ref === "<?= $escaper->escapeJs(CheckoutFieldsApi::POSTNL_HOUSE_NUMBER) ?>") {
                                return !value || this.houseNumberRegex.test(value);
                            } else if (ref === "<?= $escaper->escapeJs(CheckoutFieldsApi::POSTNL_HOUSE_NUMBER_ADDITION) ?>") {
                                return true;
                            }
                            return false;
                        },
                        validateHTMLSelectElement: (ref) => {
                            if (!(ref in this.address)) {
                                return false;
                            }

                            return this.$refs[ref].checkValidity();
                        },
                        validateDifference: (ref, newValue, previousValue) => {
                            return newValue !== previousValue
                        },
                        validateCompletion: (ref) => {
                            return Array.prototype.every.call(this.address, (value, index) => typeof value === 'string' && (value.trim() !== '' || index === 'postnl_housenumber_addition'));
                        }
                    }
                }
            },

            errorMessage: '',

            dispatchMessage: function(message, type = 'error') {
                if (['error', 'warning'].includes(type)) {
                    this.errorMessage = message;
                } else {
                    this.errorMessage = '';
                }
            }
        }
    }
</script>
<?php if (isset($hyvaCsp)) $hyvaCsp->registerInlineScript() ?>
