<?php
declare(strict_types=1);

/** @var Escaper $escaper */

use Magento\Framework\Escaper;
?>

<script>
    (() => {
        if (hyva && hyva.formValidation) {
            hyva.formValidation.addRule('validate-house-number', function(value, options, field, context) {
                const houseNumberRegex = /[1-9]\d{0,4}(?:\D.*)?$/i;
                const isHouseNumberValid = houseNumberRegex.test(value)

                if (!value || isHouseNumberValid) {
                    return true;
                } else {
                    return '<?= $escaper->escapeJs(__('Please enter a valid house number.')); ?>';
                }
            })
        }
    })();
</script>
<?php if (isset($hyvaCsp)) $hyvaCsp->registerInlineScript() ?>
