<?php
use Hyva\Checkout\Model\Form\AbstractEntityForm;
use Hyva\Checkout\Model\Form\EntityFieldInterface;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Customer\Api\Data\AddressInterface;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PostNL\HyvaCheckout\Api\CheckoutFieldsApi;

/** @var Template $block */
/** @var EntityFieldInterface $postcodeElement */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var AbstractEntityForm $form */

$element = $block->getData('element');
$form = $element->getForm();

$postcodeField = $form->getField(AddressInterface::POSTCODE);
$houseNumberField = $form->getField(CheckoutFieldsApi::POSTNL_HOUSE_NUMBER);
$houseNumberAdditionField = $form->getField(CheckoutFieldsApi::POSTNL_HOUSE_NUMBER_ADDITION);
?>
<div x-data="postnlAddressValidationAlpine"
     x-init="postnlAddressValidationInit"
     class="postnl-validation-block w-full font-medium text-gray-500 space-y-4"
     wire:key="postnl_validation_<?= $escaper->escapeHtmlAttr($form->getNamespace()) ?>"
>
    <!-- Custom inline error message -->
    <div x-show="errorMessage" class="bg-red-100 border border-red-300 text-red-800 px-4 py-2 rounded">
        <p x-text="errorMessage"></p>
    </div>

    <div class="flex-container flex flex-row gap-4">
        <div class="flex-block flex-1">
            <?= /* @noEscape */ $postcodeField->render() ?>
        </div>

        <div class="flex-block flex-1">
            <?= /* @noEscape */ $houseNumberField->render() ?>
        </div>

        <div class="flex-block flex-1">
            <?= /* @noEscape */ $houseNumberAdditionField->render() ?>
        </div>
    </div>
</div>
