<?php
use PostNL\HyvaCheckout\Magewire\SelectTimeframe;
use PostNL\HyvaCheckout\ViewModel\CheckoutView;
use PostNL\HyvaCheckout\ViewModel\ShippingView;

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Hyva\Theme\Model\ViewModelRegistry $viewModels */
/** @var SelectTimeframe $magewire */
/** @var CheckoutView $checkoutView */

/** @var \Hyva\PostNL\ViewModel\Location $locationViewModel */
$checkoutView = $viewModels->require(CheckoutView::class);

/** @var ShippingView $shippingViewModel */
$shippingViewModel = $viewModels->require(ShippingView::class);

?>
<div>
    <?php if ($magewire->isOpen() && $shippingViewModel->getDeliveryPrice() !== null): ?>
        <div class="min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
            <div class="sm:flex sm:items-start">
                <div class="w-full border-2 border-postnl-gray-lighter">
                    <?php foreach ($magewire->getTimeframes() as $dayData): ?>
                    <?php if ($dayData->getDate()): ?>
                        <strong class="shipping-timeframe flex w-full bg-postnl-gray-light justify-start text-postnl-gray-darker
                            py-3 px-4 border-t-2 border-b-2 border-postnl-gray-lighter">
                            <span class="deliverydays-day uppercase"><?= $escaper->escapeHtml(__(date('l', strtotime($dayData->getDate())))) ?>, </span>
                            <span class="deliverydays-date"> <?= $escaper->escapeHtml($dayData->getDate()) ?></span>
                        </strong>
                    <?php endif; ?>
                    <ul class="flex flex-col gap-2 p-4">
                        <?php foreach ($dayData->getOptions() as $optionTimeframe): ?>
                        <li class="flex items-center">
                            <input type="radio"
                                   id="timeframe-<?= $escaper->escapeHtmlAttr($optionTimeframe->getValue()) ?>"
                                   value="<?= $escaper->escapeHtmlAttr($optionTimeframe->getValue()) ?>"
                                   class="peer"
                                   required
                                   wire:model="deliveryTimeframe">

                            <label for="timeframe-<?= $escaper->escapeHtmlAttr($optionTimeframe->getValue()) ?>"
                                   class="timeframe-btn w-full flex justify-between ml-3 text-postnl-gray-darker">
                                <span><?= $escaper->escapeHtml($optionTimeframe->getLabel()) ?></span>
                                <div class="right-label">
                                    <?php if ($optionTimeframe->getRightLabel()): ?>
                                        <span><?= $escaper->escapeHtml($optionTimeframe->getRightLabel()) ?></span>
                                        <?php if ($optionTimeframe->getFee()): ?>
                                            (<span class="price">+ <?= $escaper->escapeHtml($optionTimeframe->getFee()) ?></span>)
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </label>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <?php if ($magewire->canUseStatedAddressOnly()): ?>
            <div class="extra-service-container my-8">
                <div class="extra-service-header bg-postnl-gray-darker text-white py-3 px-4">
                    <span class="extra-service-label uppercase"><?= $escaper->escapeHtml(__('Extra service')) ?></span>
                </div>

                <div class="only-stated-address flex items-center p-4 border border-postnl-gray-lighter">
                    <input type="checkbox"
                           name="postnl_stated_address_only_checkbox"
                           id="postnl_stated_address_only_checkbox"
                           value="1"
                           class="checkbox"
                           wire:model="statedOnly">
                    <div class="extra-service-info w-full flex justify-between text-postnl-gray-darker ml-3">
                        <label for="postnl_stated_address_only_checkbox"><?= $escaper->escapeHtml(__('Do not deliver to neighbours')); ?></label>
                        <?php if ($statedFee = $magewire->statedAddressOnlyFee()): ?>
                            <span class="price">+ <?= /** @noEscape */$statedFee ?></span>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>
